# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('work_place', models.CharField(max_length=254)),
                ('company', models.CharField(max_length=254)),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
